name: Build and test runtime

on:
  workflow_dispatch:
  push:
    branches: "*"
  pull_request: 
    branches: "master"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        container:
          - ubuntu-2204
          - fedora-39
    container:
      image: "manjusakalza/bpftime-base-image:${{matrix.container}}"
      options: --privileged
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Build
      run: |
        cmake -DBPFTIME_LLVM_JIT=YES -DBPFTIME_ENABLE_UNIT_TESTING=YES -DCMAKE_BUILD_TYPE=Debug -B build
        cmake --build build --config Debug --target bpftime_runtime_tests -j$(nproc)
    - name: Test Runtime
      run:  ./build/runtime/unit-test/bpftime_runtime_tests

    - name: build runtime with mpk enable
      run: |
        rm -rf build
        cmake -Bbuild -DBPFTIME_LLVM_JIT=YES  -DBPFTIME_ENABLE_UNIT_TESTING=YES -DBPFTIME_ENABLE_MPK=YES -DCMAKE_BUILD_TYPE=Debug
        cmake --build build --config Debug --target bpftime_runtime_tests -j$(nproc)


    - name: test runtime with mpk
      run:  ./build/runtime/unit-test/bpftime_runtime_tests
    
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
